name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pep517
        run: >-
          python -m
          pip install
          pep517
          --user 
    
      - name: Install dev dependencies
        run: >-
          pip install -r requirements-dev.txt
    
      - name: Code Quality
        run: black . --check

      - name: Test with pytest
        run: pytest . -n 2
